spectehnika/core/forms.py
from wtforms import Form, DateField, BooleanField, StringField, IntegerField, SelectField, FormField, validators

from auth.models import Machine, Owner, MachineTypes


class ReportRowForm(Form):
    date1 = DateField('дата')
    date2 = DateField('конечная дата')
    owner = SelectField('поставщик')
    machine = SelectField('тип техник')
    model = SelectField('модель')
    hours = StringField('часы')
    address = StringField('адрес')
    cost = IntegerField('закупка')
    price = IntegerField('продажа')

    def __init__(self, formdata=None, obj=None, prefix="", data=None, meta=None, **kwargs):
        super().__init__(formdata, obj, prefix, data, meta, **kwargs)
        owners = Owner.select(Owner.id, Owner.title)
        owner_choices = [(owner.id, owner.title) for owner in owners]
        owner_choices.insert(0, (0, 'Не выбрано'))
        self.owner.choices = owner_choices


class ReportForm(Form):
    row1 = FormField(ReportRowForm)
    row2 = FormField(ReportRowForm)
    row3 = FormField(ReportRowForm)
    row4 = FormField(ReportRowForm)
    row5 = FormField(ReportRowForm)


class GetReportForm(Form):
    date1 = DateField('дата', validators=[validators.InputRequired()])
    date2 = DateField('конечная дата', validators=[validators.InputRequired()])
    owner = SelectField('поставщик')
    machine = SelectField('тип техник')
    model = SelectField('модель')

    def __init__(self, formdata=None, obj=None, prefix="", data=None, meta=None, **kwargs):
        super().__init__(formdata, obj, prefix, data, meta, **kwargs)

        owners = Owner.select(Owner.id, Owner.title)
        owner_choices = [(0, 'Все')]
        owner_choices.extend([(owner.id, owner.title) for owner in owners])
        self.owner.choices = owner_choices

        machine_types = MachineTypes.select(MachineTypes.id, MachineTypes.title)
        machine_types_choices = [(0, 'Все')]
        machine_types_choices.extend([(type_.id, type_.title) for type_ in machine_types])
        self.machine.choices = machine_types_choices

        machines = Machine.select(Machine.id, Machine.model)
        machine_choices = [(0, 'Все')]
        machine_choices.extend([(machine.id, machine.model) for machine in machines])
        self.model.choices = machine_choices


class OwnerForm(Form):
    owner = StringField('наименование компании')

    def validate(self, extra_validators=None) -> bool:
        if not super().validate(extra_validators):
            return False

        owner = Owner.get_or_none(title=self.owner.data)
        if owner is None:
            return True
        else:
            self.owner.errors.append('Такая компания уже есть')
            return False


class AddSublease(Form):
    model = StringField('модель')
    type = SelectField('тип')
    number = StringField('гос номер')
    owner = SelectField('поставщик')

    def __init__(self, formdata=None, obj=None, prefix="", data=None, meta=None, **kwargs):
        super().__init__(formdata, obj, prefix, data, meta, **kwargs)
        types = MachineTypes.select(MachineTypes.id, MachineTypes.title)
        types_choices = [(type_.id, type_.title) for type_ in types]
        self.type.choices = types_choices

        owners = Owner.select(Owner.id, Owner.title)
        owner_choices = [(owner.id, owner.title) for owner in owners]
        self.owner.choices = owner_choices

    def validate(self, extra_validators=None) -> bool:
        if not super().validate(extra_validators):
            return False

        machine = Machine.get_or_none(number=self.number.data)
        if machine is not None:
            self.number.errors.append('Машина с таким номером уже есть')
            return False
        return True

spectehnika/admin/views.py
from flask import Flask, render_template, redirect, url_for, request, make_response, Blueprint, abort
from flask_login import LoginManager, login_user, logout_user, login_required, current_user

from auth.models import Machine, User, Owner, MachineTypes, Report
from core.forms import ReportForm, ReportRowForm, GetReportForm

current_user: User

bp = Blueprint('admin', __name__, url_prefix='/admin')


@bp.get('/administration')
@login_required
def administration():
    if not current_user.is_admin:
        abort(403)

    get_report = GetReportForm()
    context = {
        'get_report': get_report,
        'current_user': current_user
    }
    return render_template('admin/administration.html', **context)


@bp.get('/owners')
def owners():
    owner_id = int(request.args.get('owner'))
    machines = Machine.select(Machine.type.distinct(), Machine.owner).join(MachineTypes)
    if owner_id != 0:
        machines = machines.where(Machine.owner_id == owner_id)
    additional_choices = [
        (0, 'Все')
    ]
    context = {
        'machines': machines,
        'additional_choices': additional_choices,
    }
    return render_template('core/machines.html', **context)


@bp.get('/models')
def models():
    type_id, owner_id = map(int, request.args.get('machine').split('_'))
    models = Machine.select(Machine.id, Machine.model)
    if type_id != 0:
        models = models.where((Machine.type_id == type_id) & (Machine.owner == owner_id))

    additional_choices = [
        (0, 'Все')
    ]
    context = {
        'models': models,
        'additional_choices': additional_choices,
    }
    return render_template('core/models.html', **context)


@bp.post('report')
def get_report():
    form = GetReportForm(request.form)
    start_date = form.date1.data
    end_date = form.date2.data
    owner = int(form.owner.data)
    model = int(form.model.data)
    type = int(form.machine.data.split('_')[0])

    filters = Report.date.between(start_date, end_date)
    if owner:
        filters &= Report.owner == owner
    if type:
        filters &= Report.type == type
    if model:
        filters &= Report.model == model

    reports = (Report
               .select()
               .join(Owner)
               .where(filters))

    context = {
        'reports': reports,
        'start_date': start_date.strftime('%d.%m.%Y'),
        'end_date': end_date.strftime('%d.%m.%Y')
    }

    return render_template('report/report.html', **context)

spectehnika/core/views.py
import datetime

from flask import Flask, render_template, redirect, url_for, request, make_response, Blueprint, flash
from flask_login import login_required, current_user

from auth.models import User, Owner, Machine, Report, MachineTypes
from core.forms import ReportForm, OwnerForm, GetReportForm, AddSublease
from tehnika.forms import AddTehniks

bp = Blueprint('core', __name__, url_prefix='/core')


@bp.get('/main')
@login_required
def main():
    get_report = GetReportForm()
    form = AddSublease()
    form_owner = OwnerForm()
    report_form = ReportForm()
    tehniks = Machine.select(Machine.model, Machine.user, Machine.number).join(User).where(Machine.owner == 1)

    context = {
        'form_owner': form_owner,
        'get_report': get_report,
        'report_form': report_form,
        'tehniks': tehniks,
        'form': form,
        'current_user': current_user
    }
    return render_template('core/main.html', **context)


@bp.get('/owners')
def owners():
    keys = [arg for arg in request.args if arg.endswith('-owner')]
    if len(keys) != 1:
        raise ValueError('Multiple or none "-owner" args')

    owner_id = int(request.args[keys[0]])
    machines = Machine.select(Machine.type.distinct(), Machine.owner).join(MachineTypes)
    if owner_id:
        machines = machines.where(Machine.owner_id == owner_id)
    return render_template('core/machines.html', machines=machines)


@bp.get('/models')
def models():
    keys = [arg for arg in request.args if arg.endswith('-machine')]
    if len(keys) != 1:
        raise ValueError('Multiple or none "-owner" args')
    result = request.args[keys[0]]
    type_id, owner_id = map(int, result.split('_'))
    models = (Machine.select(Machine.id, Machine.model)
              .where((Machine.type_id == type_id) & (Machine.owner == owner_id)))
    return render_template('core/models.html', models=models)


@bp.get('/add_owner')
def add_owner():
    form_owner = OwnerForm()
    return render_template('core/add_owner.html', form_owner=form_owner)


@bp.post('/new_owner')
def new_owner():
    form = OwnerForm(request.form)
    title = form['owner'].data
    if not form.validate():
        form.owner.data = ''
        return render_template('core/add_owner.html', form=form)
    else:
        form.owner.data = ''
        Owner.create(title=title)
        return render_template('core/add_owner.html', show_success_message=1, form=form)


# @bp.get('/add_sublease')
# def add_sublease():
#     form = AddTehniks()
#     return render_template('core/sublease_form.html', form=form)
#

@bp.post('/new_sublease')
def new_sublease():
    form = AddSublease(request.form)
    if not form.validate():
        form.model.data = ''
        form.number.data = ''
        return render_template('core/sublease_form.html', form=form)

    owner = int(form.owner.data)
    model = form.model.data
    number = form.number.data
    type_ = int(form.type.data)

    form.model.data = ''
    form.number.data = ''
    Machine.create(owner=owner, model=model, number=number, type=type_, user=None)
    return render_template('core/sublease_form.html', show_success_message=1, form=form)


@bp.post('create_report')
def create_report():
    form = ReportForm(request.form)
    for row in form:
        if any(field is None for field in row.data.values()):
            continue
        date = row.data["date1"]
        end_date = row.data["date2"]

        days = 0
        day = row.data["date1"]
        while day <= end_date:
            day += datetime.timedelta(days=1)
            days += 1

        hours = int(row.data["hours"]) / days

        while date <= end_date:
            type_ = row.data["machine"].split('_')[0]
            Report.create(date=date, address=row.data["address"],
                          owner=row.data["owner"], type=type_,
                          model=row.data["model"], hours=hours,
                          cost=row.data["cost"], price=row.data["price"])
            date += datetime.timedelta(days=1)
    return redirect(url_for('core.main'))

spectehnika/templates/core/add_owner.html
<div class="box" id="add_owner">
	<p class="subtitle is-5">
		Добавить нового поставщика
	</p>
	{{ form_owner.owner.label(class='label is-small') }}
	<div class="field">
		<div class="control">
			{{ form_owner.owner(class='input is-small') }}
		</div>
	</div>
	{% if show_success_message %}
		<span class="tag is-success is-light">
							Компания добавлена
						</span>
	{% endif %}
	{% for error in form_owner.owner.errors %}
		<span class="tag is-danger is-light">
							{{ error }}
						</span>
	{% endfor %}
	<br>
	<button class="button is-warning mb-2" type="submit">Добавить</button>
</div>


{#<input class="input is-small mb-2" type="text" name="add_owner" id="add_owner">#}


{#<div class="box" id="add_owner">#}
{#	<p class="subtitle is-5">#}
{#		Добавить нового поставщика#}
{#	</p>#}
{#	<div class="field">#}
{#		<label class="label is-small">наименование компании</label>#}
{#		<div class="control">#}
{#			<input class="input is-small mb-2" type="text" name="add_owner" id="add_owner">#}
{#		</div>#}
{#	</div>#}
{#	<button class="button is-warning mb-2" type="submit">Добавить</button>#}
{#</div>#}

spectehnika/templates/core/machines.html
{% for value, title in additional_choices %}
	<option value="{{ value }}_0">{{ title }}</option>
{% endfor %}
{% for machine in machines %}
	<option value="{{ machine.type_id }}_{{ machine.owner_id }}">{{ machine.type.title }}</option>
{% endfor %}

spectehnika/templates/core/main.html
{% extends 'base/base_core.html' %}

{% block title %}
	Главная страница
{% endblock title %}

{% block page_name %}
	<p class="title is-3 is-flex is-justify-content-center">
		Табель работы спецтехники
	</p>
{% endblock %}

{% block img_under_name %}
	<img src="{{ url_for('static', filename='logo2.png') }}" alt="Logo">
{% endblock %}

{% block center_left %}
	<p class="subtitle is-4">
		Добавить данных в отчет
	</p>
	<form action="{{ url_for('core.create_report') }}" method="POST">
		{% for row in report_form %}
			<div class="columns">
				{% for field in row if field.widget.input_type != 'hidden' %}
					<div class="column">
						<div class="field">
							<div class="control">
								{{ field.label(class='label is-small') }}
								{% if field.name.endswith('owner') %}
									<select class="input is-small" name="{{ field.name }}"
									        id="owner_{{ field.name.split('-')[0] }}"
									        hx-get="{{ url_for('core.owners') }}"
									        hx-target="#machines_{{ field.name.split('-')[0] }}">
										{% for value, display in field.choices %}
											<option value="{{ value }}">{{ display }}</option>
										{% endfor %}
									</select>
								{% elif field.name.endswith('machine') %}
									<select class="input is-small" name="{{ field.name }}"
									        id="machines_{{ field.name.split('-')[0] }}"
									        hx-get="{{ url_for('core.models') }}"
									        hx-target="#models_{{ field.name.split('-')[0] }}">
										{{ field(class='input is-small', id='teh') }}
									</select>
								{% elif field.name.endswith('model') %}
									<select class="input is-small" name="{{ field.name }}"
									        id="models_{{ field.name.split('-')[0] }}">
										{{ field(class='input is-small', id='teh') }}
									</select>
									{#  {{ field(class='input is-small', id="models") }}#}
								{% else %}
									{{ field(class='input is-small') }}
								{% endif %}
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		{% endfor %}
		<button class="button is-warning mt-5" type="submit">Отправить</button>
	</form>
{% endblock center_left %}

{% block center_right %}
	<form action="{{ url_for('admin.get_report') }}" method="POST">
		<div class="box">
			<p class="subtitle is-4">
				Сформировать отчет
			</p>
			<div class="field">
				{{ get_report.date1.label(class='label is-small') }}
				<div class="control">
					{{ get_report.date1(class='input is-small') }}
				</div>
			</div>
			<div class="field">
				{{ get_report.date2.label(class='label is-small') }}
				<div class="control">
					{{ get_report.date2(class='input is-small') }}
				</div>
				<br>
			</div>
			<p class="subtitle is-5">
				Выберите технику
			</p>
			<div class="field">
				{{ get_report.owner.label(class='label is-small') }}
				<div class="control">
					<select class="input is-small" name="owner" id="owner"
					        hx-get="{{ url_for('admin.owners') }}"
					        hx-target="#machines2">
						{% for value, display in get_report.owner.choices %}
							<option value="{{ value }}">{{ display }}</option>
						{% endfor %}
					</select>
				</div>
			</div>
			<div class="field">
				{{ get_report.machine.label(class='label is-small') }}
				<div class="control">
					<select class="input is-small" name="machine" id="machines2"
					        hx-get="{{ url_for('admin.models') }}"
					        hx-target="#models2">
						{% for value, display in get_report.machine.choices %}
							<option value="{{ value }}">{{ display }}</option>
						{% endfor %}
					</select>
				</div>
			</div>
			<div class="field">
				{{ get_report.model.label(class='label is-small') }}
				<div class="control">
					{{ get_report.model(class='input is-small', id='models2') }}
				</div>
			</div>
			<button class="button is-warning mt-3" type="submit">Выполнить</button>
		</div>
	</form>
{% endblock center_right %}

{% block footer %}
	<div class="columns">
		<div class="column">
			<form hx-post="{{ url_for('core.new_sublease') }}" hx-target="#new_sublease" hx-swap="outerHTML">
				{% include'core/sublease_form.html' with context %}
			</form>
		</div>
		<div class="column is-3">
			<form hx-post="{{ url_for('core.new_owner') }}" hx-target="#add_owner" hx-swap="outerHTML">
				{% include 'core/add_owner.html' with context %}
			</form>
		</div>
	</div>
{% endblock footer %}

spectehnika/templates/core/models.html
{% for value, title in additional_choices %}
	<option value="{{ value }}">{{ title }}</option>
{% endfor %}
{% for model in models %}
	<option value="{{ model.id }}">{{ model.model }}</option>
{% endfor %}

spectehnika/templates/core/sublease_form.html
<div class="box" id="new_sublease">
	<p class="subtitle is-4">
		Добавить технику в базу
	</p>
	<div class="columns">
		<div class="column">
			<div class="field">
				{{ form.owner.label(class='label is-small') }}
				<div class="control">
					{{ form.owner(class='input is-small') }}
					{#					<select class="input is-small" name="owner" id="choose_owner">#}
					{#						{% for value, display in form.owner.choices %}#}
					{#							<option value="{{ value }}">{{ display }}</option>#}
					{#						{% endfor %}#}
					{#					</select>#}
				</div>
			</div>
		</div>
		<div class="column">
			<div class="field">
				{{ form.model.label(class='label is-small') }}
				<div class="control">
					{{ form.model(class='input is-small') }}
				</div>
			</div>
		</div>
		<div class="column">
			<div class="field">
				{{ form.number.label(class='label is-small') }}
				<div class="control">
					{{ form.number(class='input is-small') }}
				</div>
			</div>
			{% for error in form.number.errors %}
				<span class="tag is-danger is-light">
					{{ error }}
				</span>
			{% endfor %}
			{% if show_success_message %}
				<span class="tag is-success is-light">
					Машина добавлена
				</span>
			{% endif %}
		</div>
		<div class="column">
			<div class="field">
				{{ form.type.label(class='label is-small') }}
				<div class="control">
					<select class="input is-small" name="type" id="choose_type">
						{% for value, display in form.type.choices %}
							<option value="{{ value }}">{{ display }}</option>
						{% endfor %}
					</select>
				</div>
			</div>
		</div>
	</div>
	<button class="button is-warning" type="submit">Добавить</button>
</div>