spectehnika/reports/views.py
from flask import Flask, render_template, redirect, url_for, request, make_response, Blueprint, flash
from flask_login import LoginManager, login_user, logout_user, login_required, current_user

from auth.models import Machine, User, MachineTypes, Owner, Report

bp = Blueprint('rep', __name__, url_prefix='/rep')


@bp.get('report/<int:id>')
def report_row(id: int):
    context = {
        'row': Report.get_by_id(id)
    }
    return render_template('report/report_row.html', **context)


@bp.get('report/<int:id>/edit')
def get_edit_report(id: int):
    context = {
        'row': Report.get_by_id(id)
    }
    return render_template('report/edit_report.html', **context)


@bp.put('report/<int:id>')
def put_edit_report(id: int):
    report = Report.get_by_id(id)
    report.hours = request.form['hours']
    report.cost = request.form['cost']
    report.price = request.form['price']
    report.save()

    context = {
        'row': Report.get_by_id(id)
    }
    return render_template('report/report_row.html', **context)


@bp.delete('del_report/<int:id>')
def del_report(id: int):
    Report.delete_by_id(id)
    return ''

spectehnika/templates/report/edit_report.html
<tr>
	<td>
		{{ row.date.strftime('%d.%m.%Y') }}
	</td>
	<td>
		{{ row.address }}
	</td>
	<td>
		{{ row.type.title }}
	</td>
	<td>
		{{ row.model.model }}
	</td>
	<td>
		{{ row.owner.title }}
	</td>
	<td>
		<input class="input" type="text" name="hours" value="{{ row.hours }}">
	</td>
	<td>
		<input class="input" type="text" name="cost" value="{{ row.cost }}">
	</td>
	<td>
		<input class="input" type="text" name="price" value="{{ row.price }}">
	</td>
	<td>
		{{ row.cost * row.hours / 8 }}
	</td>
	<td>
		{{ row.price * row.hours / 8 }}
	</td>
	<td>
		<button class="button is-success is-normal"
		        hx-put="{{ url_for('rep.put_edit_report', id=row.id) }}"
		        hx-include="closest tr">SAVE
		</button>
	</td>
	<td>
		<button class="button is-info is-normal"
		        hx-get="{{ url_for('rep.report_row', id=row.id) }}">CANCEL
		</button>
	</td>
</tr>

spectehnika/templates/report/report.html
{% extends 'base/base_core.html' %}

{% block title %}
	Отчет по работе спецтехники
{% endblock title %}

{% block page_name %}
	<p>
		<span class="title mb-0 is-3 is-flex is-justify-content-center">
			Табель работы спецтехники
		</span><br>
		<span class="title mt-0 is-4 is-flex is-justify-content-center">
			с {{ start_date }} по {{ end_date }}
		</span>
	</p>
{% endblock %}

{% block body %}

	<div class="container">
		<div class="box">
			<table class="table">
				<thead>
					<tr>
						<th>
							дата
						</th>
						<th>
							адрес
						</th>
						<th>
							тип техники
						</th>
						<th>
							модель
						</th>
						<th>
							поставщик
						</th>
						<th>
							часы
						</th>
						<th>
							закупка
						</th>
						<th>
							продажа
						</th>
						<th>
							ст.закупки
						</th>
						<th>
							ст.продажи
						</th>
					</tr>
				</thead>
				<tbody hx-target="closest tr" hx-swap="outerHTML swap:1s">
					{% for row in reports %}
						{% include 'report/report_row.html' with context %}
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
{% endblock %}

spectehnika/templates/report/report_row.html
<tr>
	<td>
		{{ row.date.strftime('%d.%m.%Y') }}
	</td>
	<td>
		{{ row.address }}
	</td>
	<td>
		{{ row.model.type.title }}
	</td>
	<td>
		{{ row.model.model }}
	</td>
	<td>
		{{ row.owner.title }}
	</td>
	<td>
		{{ row.hours }} ч.
	</td>
	<td>
		{{ row.cost }} руб.
	</td>
	<td>
		{{ row.price }} руб.
	</td>
	<td>
		{{ row.price * row.hours / 8 }}
	</td>
	<td>
		{{ row.cost * row.hours / 8 }}
	</td>
	<td>
		<button class="button is-success is-normal" hx-get="{{ url_for('rep.get_edit_report', id=row.id) }}">EDIT
		</button>
	</td>
	<td>
		<button class="button is-danger is-normal" hx-delete="{{ url_for('rep.del_report', id=row.id) }}"
		        hx-confirm="Вы действительно хотите удалить">DEL
		</button>
	</td>
</tr>