spectehnika/tehnika/forms.py
from wtforms import Form, DateField, BooleanField, StringField, IntegerField, SelectField, EmailField, PasswordField
from wtforms.validators import InputRequired, Length


from auth.models import MachineTypes, Machine, User, Owner


class AddTehniks(Form):
    model = StringField('модель')
    type = SelectField('тип')
    number = StringField('гос номер')
    owner = SelectField('поставщик')
    user = SelectField('машинист')

    def __init__(self, formdata=None, obj=None, prefix="", data=None, meta=None, **kwargs):
        super().__init__(formdata, obj, prefix, data, meta, **kwargs)
        types = MachineTypes.select(MachineTypes.id, MachineTypes.title)
        types_choices = [(type_.id, type_.title) for type_ in types]
        self.type.choices = types_choices

        users = User.select(User.id, User.name)
        users_choice = [(user.id, user.name) for user in users]
        self.user.choices = users_choice

        owners = Owner.select(Owner.id, Owner.title)
        owner_choices = [(owner.id, owner.title) for owner in owners]
        self.owner.choices = owner_choices

    def validate(self, extra_validators=None) -> bool:
        if not super().validate(extra_validators):
            return False

        machine = Machine.get_or_none(number=self.number.data)
        if machine is not None:
            self.number.errors.append('Машина с таким номером уже есть')
            return False
        return True



class AddType(Form):
    title = StringField('тип техники')

    def __init__(self, formdata=None, obj=None, prefix="", data=None, meta=None, **kwargs):
        super().__init__(formdata, obj, prefix, data, meta, **kwargs)
        types = MachineTypes.select(MachineTypes.id, MachineTypes.title)
        types_choices = [(type_.id, type_.title) for type_ in types]
        self.title.choices = types_choices

    def validate(self, extra_validators=None) -> bool:
        if not super().validate(extra_validators):
            return False

        type_ = MachineTypes.get_or_none(title=self.title.data)
        if type_ is None:
            return True
        else:
            self.title.errors.append('Такой тип уже есть')
            return False

spectehnika/tehnika/views.py
from flask import Flask, render_template, redirect, url_for, request, make_response, Blueprint, flash
from flask_login import LoginManager, login_user, logout_user, login_required, current_user

from auth.models import Machine, User, MachineTypes, Owner
from tehnika.forms import AddTehniks, AddType

bp = Blueprint('teh', __name__, url_prefix='/teh')


@bp.get('/tehnika')
@login_required
def tehnika():
    type_form = AddType()
    form = AddTehniks()
    tehniks = Machine.select().join(User).where(Machine.owner == 1).order_by(Machine.id)

    context = {
        'tehniks': tehniks,
        'form': form,
        'type_form': type_form
    }
    return render_template('teh/tehnika.html', **context)


# @bp.get('/tehnika_form')
# def tehnika_form():
#     form = AddTehniks()
#     return render_template('teh/tehnika_form.html', form=form)


@bp.post('/add_tehnika')
def add_tehnika():
    form = AddTehniks(request.form)

    if not form.validate():
        form.model.data = ''
        form.user.data = ''
        return render_template('teh/tehnika_form.html', form=form)

    model = form.model.data
    number = form.number.data
    type_id = int(form.type.data)
    user_id = int(form.user.data)
    owner_id = 1
    Machine.create(model=model, number=number, type=type_id, user=user_id, owner=owner_id)

    form.model.data = ''
    form.number.data = ''
    return render_template('teh/tehnika_form.html', form=form, show_success_message=1)


@bp.get('/type_form')
def type_form():
    type_form = AddType()
    render_template('teh/type_form.html', type_form=type_form)


@bp.post('/add_type')
def add_type():
    type_form = AddType(request.form)
    if not type_form.validate():
        type_form.title.data = ''
        return render_template('teh/type_form.html', type_form=type_form)
    new_type = MachineTypes()
    type_form.populate_obj(new_type)
    new_type.save()
    type_form.title.data = ''
    return render_template('teh/type_form.html', type_form=type_form, show_success_mesage=1)


@bp.get('machine/<int:id>')
def row_machine(id: int):
    context = {
        'tehnika': Machine.get_by_id(id)
    }
    return render_template('teh/row_machine.html', **context)


@bp.delete('del_tehnika/<int:id>')
def del_tehnika(id: int):
    Machine.delete_by_id(id)
    return ''


@bp.get('machine/<int:id>/edit')
def get_edit_row(id: int):
    context = {
        'tehnika': Machine.get_by_id(id)
    }
    return render_template('teh/edit_machine.html', **context)


@bp.put('machine/<int:id>')
def put_edit_row(id: int):
    machine = Machine.get_by_id(id)
    machine.model = request.form['model']
    machine.user = request.form['user']
    machine.number = request.form['number']
    machine.save()

    context = {
        'tehnika': Machine.get_by_id(id)
    }
    return render_template('teh/row_machine.html', **context)

spectehnika/templates/teh/edit_machine.html
<tr>
	<td><input class="input" type="text" name="model" value="{{ tehnika.model }}"></td>
	<td><input class="input" type="text" name="user" value="{{ tehnika.user }}"></td>
	<td><input class="input" type="text" name="number" value="{{ tehnika.number }}"></td>
	<td>
		<button class="button is-success is-normal"
		        hx-put="{{ url_for('teh.put_edit_row', id=tehnika.id) }}"
		        hx-include="closest tr">SAVE</button>
	</td>
	<td>
		<button class="button is-info is-normal"
		        hx-get="{{ url_for('teh.row_machine', id=tehnika.id) }}">CANCEL</button>
	</td>
	<td>
		<button class="button is-danger is-normal"
		        hx-delete="del_tehnika/{{ tehnika.id }}">DEL</button>
	</td>
</tr>

spectehnika/templates/teh/row_machine.html
<tr>
	<td>
		{{ tehnika.model }}
	</td>
	<td>
		{{ tehnika.user.name }}
	</td>
	<td>
		{{ tehnika.number }}
	</td>
	<td>
		<button class="button is-success is-normal" hx-get="{{ url_for('teh.get_edit_row', id=tehnika.id) }}">EDIT</button>
	</td>
	<td>
		<button class="button is-danger is-normal" hx-delete="del_tehnika/{{ tehnika.id }}" hx-confirm="Вы действительно хотите удалить" >DEL</button>
	</td>
</tr>

spectehnika/templates/teh/tehnika.html
{% extends 'base/base_page.html' %}

{% block title %}
	Редактирование и добавление техники
{% endblock title %}

{% block page_name %}
	<p class="title is-3 is-flex is-justify-content-center">
		Парк техники
	</p>
{% endblock %}

{% block img_under_name %}
{% endblock %}

{% block body %}
	<div class="container">
		<br><br><br>
		<div class="block">
			<div class="columns">
				<div class="column">
					<div class="box">
						<p class="subtitle is-4">
							Редактирование техники
						</p>
						<br>
						<form>
							<table class="table mb-6 mt-1">
								<thead>
									<tr>
										<th>модель</th>
										<th>машинист</th>
										<th>гос номер</th>
									</tr>
								</thead>
								<tbody hx-target="closest tr"
								       hx-swap="outerHTML swap:1s">
									{% for tehnika in tehniks %}
										{% include 'teh/row_machine.html' with context %}
									{% endfor %}
								</tbody>
							</table>
						</form>
					</div>
				</div>
				<div class="column">
					<form hx-post="{{ url_for('teh.add_tehnika') }}" hx-target="#add_tehnika" hx-swap="outerHTML">
						{% include 'teh/tehnika_form.html' with context %}
					</form>
					<form hx-post="{{ url_for('teh.add_type') }}" hx-target="#add_type" hx-swap="outerHTML">
						{% include 'teh/type_form.html' with context %}
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock body %}

spectehnika/templates/teh/tehnika_form.html
<div class="box" id="add_tehnika">
	<p class="subtitle is-4">
		Добавить собственную технику
	</p>
	<br><br>
	<div class="columns">
		<div class="column">
			<div class="field">
				{{ form.model.label(class='label is-small') }}
				<div class="control">
					{{ form.model(class='input is-small') }}
				</div>
			</div>
			<div class="field">
				{{ form.number.label(class='label is-small') }}
				<div class="control">
					{{ form.number(class='input is-small') }}
				</div>
			</div>
			{% if show_success_message %}
				<span class="tag is-success is-light">
					Машина добавлена
				</span>
			{% endif %}
			{% for error in form.number.errors %}
				<span class="tag is-danger is-light">
					{{ error }}
				</span>
			{% endfor %}
		</div>
		<div class="column">
			<div class="field">
				{{ form.type.label(class='label is-small') }}
				<div class="control">
					<select class="input is-small" name="type" id="type">
						{% for value, display in form.type.choices %}
							<option value="{{ value }}">{{ display }}</option>
						{% endfor %}
					</select>
				</div>
			</div>
			<div class="field">
				{{ form.user.label(class='label is-small') }}
				<div class="control">
					<select class="input is-small" name="user" id="user">
						{% for value, display in form.user.choices %}
							<option value="{{ value }}">{{ display }}</option>
						{% endfor %}
					</select>
				</div>
				<br>
			</div>
			<div class="field" hidden>
				<div class="control">
					<select class="input is-small" name="owner" id="owner">
						{% for value, display in form.owner.choices %}
							{% if value == '1' %}
								<option value="{{ value }}" selected>{{ display }}</option>
							{% else %}
								<option value="{{ value }}">{{ display }}</option>
							{% endif %}
						{% endfor %}
					</select>
				</div>
				<br>
			</div>
			<div class="field">
				<p class="control is-flex is-justify-content-end mr-5">
					<button class="button is-success" type="submit">Добавить</button>
				</p>
			</div>
		</div>
	</div>
</div>

spectehnika/templates/teh/type_form.html
<div class="box" id="add_type">
	<p class="subtitle is-5">
		Добавить тип техники
	</p>
	<div class="columns mb-0">
		<div class="column">
			<div class="field">
				{{ type_form.title.label(class='label is-small') }}
				<div class="control">
					{{ type_form.title(class='input is-small') }}
				</div>
			</div>
			{% if show_success_mesage %}
				<span class="tag is-success is-light">
					Тип добавлен успешно
				</span>
			{% endif %}
			{% for error in type_form.title.errors %}
				<span class="tag is-danger is-light">
					{{ error }}
				</span>
			{% endfor %}
		</div>
		<div class="column is-flex is-align-items-end is-3">
			<button class="button is-success ml-2" type="submit">Добавить</button>
		</div>
	</div>
</div>