spectehnika/admin/views.py
from flask import Flask, render_template, redirect, url_for, request, make_response, Blueprint, abort
from flask_login import LoginManager, login_user, logout_user, login_required, current_user

from auth.models import Machine, User, Owner, MachineTypes, Report
from core.forms import ReportForm, ReportRowForm, GetReportForm

current_user: User

bp = Blueprint('admin', __name__, url_prefix='/admin')


@bp.get('/administration')
@login_required
def administration():
    if not current_user.is_admin:
        abort(403)

    get_report = GetReportForm()
    context = {
        'get_report': get_report,
        'current_user': current_user
    }
    return render_template('admin/administration.html', **context)


@bp.get('/owners')
def owners():
    owner_id = int(request.args.get('owner'))
    machines = Machine.select(Machine.type.distinct(), Machine.owner).join(MachineTypes)
    if owner_id != 0:
        machines = machines.where(Machine.owner_id == owner_id)
    additional_choices = [
        (0, 'Все')
    ]
    context = {
        'machines': machines,
        'additional_choices': additional_choices,
    }
    return render_template('core/machines.html', **context)


@bp.get('/models')
def models():
    type_id, owner_id = map(int, request.args.get('machine').split('_'))
    models = Machine.select(Machine.id, Machine.model)
    if type_id != 0:
        models = models.where((Machine.type_id == type_id) & (Machine.owner == owner_id))

    additional_choices = [
        (0, 'Все')
    ]
    context = {
        'models': models,
        'additional_choices': additional_choices,
    }
    return render_template('core/models.html', **context)


@bp.post('report')
def get_report():
    form = GetReportForm(request.form)
    start_date = form.date1.data
    end_date = form.date2.data
    owner = int(form.owner.data)
    model = int(form.model.data)
    type = int(form.machine.data.split('_')[0])

    filters = Report.date.between(start_date, end_date)
    if owner:
        filters &= Report.owner == owner
    if type:
        filters &= Report.type == type
    if model:
        filters &= Report.model == model

    reports = (Report
               .select()
               .join(Owner)
               .where(filters))

    context = {
        'reports': reports,
        'start_date': start_date.strftime('%d.%m.%Y'),
        'end_date': end_date.strftime('%d.%m.%Y')
    }

    return render_template('report/report.html', **context)

spectehnika/emp/views.py
from datetime import datetime, date

from flask import Flask, render_template, redirect, url_for, request, make_response, Blueprint, flash
from flask_login import LoginManager, login_user, logout_user, login_required, current_user

from emp.forms import Employee
from auth.models import User, Role, MachineTypes

bp = Blueprint('emp', __name__, url_prefix='/emp')


@bp.get('/employees')
@login_required
def employees():
    form = Employee()
    roles = Role.select(Role.id, Role.title)
    role_choises = [(role.id, role.title) for role in roles]
    form.role.choices = role_choises
    context = {
        'current_user': current_user,
        'form': form
    }
    return render_template('emp/employees.html', **context)


# @bp.get('/employee_form')
# def employee_form():
#     form = Employee()
#     render_template('emp/employee_form.html', form=form)


@bp.post('/employee')
def add_employee():
    form = Employee(request.form)
    if not form.validate():
        form.name.data = ''
        form.email.data = ''
        form.password.data = ''
        return render_template('emp/employee_form.html', form=form)

    name = form['name'].data
    role = form['role'].data
    email = form['email'].data
    password = form['password'].data
    creation_date = date.today()
    User.create(name=name, email=email, password=password, creation_date=creation_date,
                role=role, is_admin=False)
    form = Employee()
    return render_template('emp/employee_form.html', form=form, show_success_message=1)

spectehnika/tehnika/views.py
from flask import Flask, render_template, redirect, url_for, request, make_response, Blueprint, flash
from flask_login import LoginManager, login_user, logout_user, login_required, current_user

from auth.models import Machine, User, MachineTypes, Owner
from tehnika.forms import AddTehniks, AddType

bp = Blueprint('teh', __name__, url_prefix='/teh')


@bp.get('/tehnika')
@login_required
def tehnika():
    type_form = AddType()
    form = AddTehniks()
    tehniks = Machine.select().join(User).where(Machine.owner == 1).order_by(Machine.id)

    context = {
        'tehniks': tehniks,
        'form': form,
        'type_form': type_form
    }
    return render_template('teh/tehnika.html', **context)


# @bp.get('/tehnika_form')
# def tehnika_form():
#     form = AddTehniks()
#     return render_template('teh/tehnika_form.html', form=form)


@bp.post('/add_tehnika')
def add_tehnika():
    form = AddTehniks(request.form)

    if not form.validate():
        form.model.data = ''
        form.user.data = ''
        return render_template('teh/tehnika_form.html', form=form)

    model = form.model.data
    number = form.number.data
    type_id = int(form.type.data)
    user_id = int(form.user.data)
    owner_id = 1
    Machine.create(model=model, number=number, type=type_id, user=user_id, owner=owner_id)

    form.model.data = ''
    form.number.data = ''
    return render_template('teh/tehnika_form.html', form=form, show_success_message=1)


@bp.get('/type_form')
def type_form():
    type_form = AddType()
    render_template('teh/type_form.html', type_form=type_form)


@bp.post('/add_type')
def add_type():
    type_form = AddType(request.form)
    if not type_form.validate():
        type_form.title.data = ''
        return render_template('teh/type_form.html', type_form=type_form)
    new_type = MachineTypes()
    type_form.populate_obj(new_type)
    new_type.save()
    type_form.title.data = ''
    return render_template('teh/type_form.html', type_form=type_form, show_success_mesage=1)


@bp.get('machine/<int:id>')
def row_machine(id: int):
    context = {
        'tehnika': Machine.get_by_id(id)
    }
    return render_template('teh/row_machine.html', **context)


@bp.delete('del_tehnika/<int:id>')
def del_tehnika(id: int):
    Machine.delete_by_id(id)
    return ''


@bp.get('machine/<int:id>/edit')
def get_edit_row(id: int):
    context = {
        'tehnika': Machine.get_by_id(id)
    }
    return render_template('teh/edit_machine.html', **context)


@bp.put('machine/<int:id>')
def put_edit_row(id: int):
    machine = Machine.get_by_id(id)
    machine.model = request.form['model']
    machine.user = request.form['user']
    machine.number = request.form['number']
    machine.save()

    context = {
        'tehnika': Machine.get_by_id(id)
    }
    return render_template('teh/row_machine.html', **context)

spectehnika/templates/base/base_core.html
{% extends 'base/base_page.html' %}

{% block body %}
	<div class="block">
		<div class="container">
			<div class="columns">
				<div class="column">
					<div class="box">
						{% block center_left %}{% endblock center_left %}
					</div>
				</div>
				<div class="column is-one-quarter">
					{% block center_right %}{% endblock center_right %}
				</div>
			</div>
		</div>
	</div>

	<div class="block">
		<div class="container">
			{% block footer %}{% endblock footer %}
		</div>
	</div>
{% endblock body %}

spectehnika/templates/base/base_page.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title> {% block title %} {% endblock %} </title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
	<link rel="stylesheet" href={{ url_for('static', filename='style.css') }}>
	<script src="https://kit.fontawesome.com/9f0d5e374e.js" crossorigin="anonymous"></script>
	<script src="https://unpkg.com/htmx.org@1.9.8"
	        integrity="sha384-rgjA7mptc2ETQqXoYC3/zJvkU7K/aP44Y+z7xQuJiVnB/422P/Ak+F/AqFR7E4Wr"
	        crossorigin="anonymous"></script>
</head>
<body>
	<div class="block pb-4">
		<div class="container">
			<div class="columns">
				<div class="column is-one-fifth">
					<img src="{{ url_for('static', filename='logo.png') }}" alt="Logo">
				</div>
				<div class="column is-flex is-justify-content-center">
					<div class="block is-flex is-justify-content-center is-flex-direction-column mt-6">
						{% block page_name %}{% endblock %}
						<br>
						{% block img_under_name %}{% endblock %}
					</div>
				</div>
				<div class="column is-one-fifth">
					<div class="columns">
						{% if current_user.id == 1 %}
							<div class="column">
								<a href="{{ url_for('admin.administration') }}">
							<span class="icon">
								<i class="fa-sharp fa-solid fa-house-chimney fa-lg" style="color: #ffc31f;"></i>
							</span>
								</a>
							</div>
							<div class="column">
								<a href="{{ url_for('core.main') }}">
							<span class="icon">
								<i class="fa-solid fa-list-check fa-lg" style="color: #ffc31f;"></i>
							</span>
								</a>
							</div>
							<div class="column">
								<a href="{{ url_for('emp.employees') }}">
							<span class="icon">
								<i class="fa-sharp fa-solid fa-people-roof fa-lg" style="color: #ffc31f;"></i>
							</span>
								</a>
							</div>
							<div class="column">
								<a href="{{ url_for('teh.tehnika') }}">
							<span class="icon">
								<i class="fa-solid fa-tractor fa-lg" style="color: #ffc31f;"></i>
							</span>
								</a>
							</div>
							<div class="column">
								<a href="{{ url_for('auth.logout') }}">
							<span class="icon">
								<i class="fa-sharp fa-solid fa-right-from-bracket fa-lg" style="color: #ffc31f;"></i>
							</span>
								</a>
							</div>

						{% else %}
							<div class="column">
								<a href="{{ url_for('core.main') }}">
							<span class="icon">
								<i class="fa-sharp fa-solid fa-house-chimney fa-lg" style="color: #ffc31f;"></i>
							</span>
								</a>
							</div>
							<div class="column">
								<a href="">
							<span class="icon">
								<i class="fa-solid fa-list-check fa-lg" style="color: #ffc31f;"></i>
							</span>
								</a>
							</div>
							<div class="column">
								<a href="{{ url_for('auth.logout') }}">
							<span class="icon">
								<i class="fa-sharp fa-solid fa-right-from-bracket fa-lg" style="color: #ffc31f;"></i>
							</span>
								</a>
							</div>
							<div class="column"></div>
							<div class="column"></div>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</div>

	{% block body %}{% endblock %}

	<div class="notifications">
		{% for message in get_flashed_messages() %}
			<div class="notification">
				<button class="delete"></button>
				{{ message }}
			</div>
		{% endfor %}
	</div>
	<script>
        document.addEventListener('DOMContentLoaded', () => {
            (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
                const $notification = $delete.parentNode;

                $delete.addEventListener('click', () => {
                    $notification.parentNode.removeChild($notification);
                });
            });
        });
	</script>

</body>
</html>